# Generated by Django 2.1.1 on 2018-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('sregno', models.CharField(max_length=10)),
            ],
        ),
    ]
