# Generated by Django 2.1.1 on 2018-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'computer science engineering'), ('ece', 'electronics and communication engineering'), ('it', 'information technologies')], default=1, max_length=64, verbose_name='Student'),
            preserve_default=False,
        ),
    ]
