# Generated by Django 2.1.1 on 2018-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'computer science engineering'), ('ece', 'electronics and communication engineering'), ('it', 'information technologies')], max_length=64, verbose_name='Branch'),
        ),
    ]
