# Generated by Django 2.1.1 on 2018-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20180926_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('s&h', 'science and humanities'), ('eee', 'electrical and electronical engineering'), ('me', 'mechanical engineering'), ('civil', 'civil engineering'), ('cse', 'computer science engineering'), ('ece', 'electronics and communication engineering'), ('it', 'information technologie')], max_length=64, verbose_name='Branch'),
        ),
    ]
