# Generated by Django 2.1.1 on 2018-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_auto_20180927_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sregno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
